### ISSUE TITLE
TDS2024B : Config export to TOML file separates string fields into lists

### ISSUE THREAD

**Issue by fdmysterious** [fdmysterious/python-lab-control#2]
For example:

```python
from instr.tds2024b import TDS2024B_Interface
import toml

osc = TDS2024B_Interface()

osc.settings_read()
conf = osc.settings_dump()

with open('settings.toml', 'w') as fhandle:
    toml.dump(conf, fhandle)
```

Gives the following file:

```toml
[trigger]
type = [ "E", "D", "G", "E",]
mode = [ "A", "U", "T", "O",]
level = 2.0
edge_coupling = [ "D", "C",]
edge_slope = [ "F", "A", "L", "L",]
edge_source = [ "C", "H", "1",]

[horizontal_main]
pos = 0.0
scale = 0.0001

[horizontal_delay]
pos = 0.0
scale = 0.0001

[ch1]
bw_filter = false
coupling = [ "D", "C",]
invert = false
position = 0.0
attenuation = 10.0
scale = 1.0
on = true

[ch2]
bw_filter = false
coupling = [ "D", "C",]
invert = false
position = 0.0
attenuation = 10.0
scale = 1.0
on = true

[ch3]
bw_filter = false
coupling = [ "D", "C",]
invert = false
position = 0.0
attenuation = 10.0
scale = 1.0
on = true

[ch4]
bw_filter = false
coupling = [ "D", "C",]
invert = false
position = -2.0
attenuation = 10.0
scale = 0.5
on = false

[mes1]
source = [ "C", "H", "1",]
type = [ "N", "W", "I", "D", "T", "H",]

[mes2]
source = [ "C", "H", "2",]
type = [ "N", "W", "I", "D", "T", "H",]

[mes3]
source = [ "C", "H", "3",]
type = [ "N", "W", "I", "D", "T", "H",]

[mes4]
source = [ "M", "A", "T", "H",]
type = [ "N", "W", "I", "D", "T", "H",]

[mes_imm]
source = [ "C", "H", "1",]
type = [ "P", "E", "R", "I", "O", "D",]
```

String fields are separated into lists.
